### ISSUE TITLE
Fleetms since 0.1.32 not starting properly

### ISSUE THREAD

**Issue by djones6** [ibm-cloud-architecture/refarch-kc-ms#60]
Further to recent comment in #58
When starting fleetms from the 0.1.32 image, I see this message logged:
```
CWWKZ0014W: The application fleetms could not be started as it could not be found at location fleetms.war.
```

It does not seem to be serving any of the /fleetms routes successfully.

Looks like the war file is being built with a different name to what was expected (`fleetms.war`):
```
sh-4.4$ find . -name "fleetms*"
./usr/servers/defaultServer/apps/fleetms-1.0-SNAPSHOT.war
```

There's probably a setting in the pom.xml that controls this, but that's not something I have a lot of experience with.

**Comment by djones6** [comment]
@josiemundi FYI 😄

**Comment by josiemundi** [comment]
@djones6 I have taken a look and notice that fleetms pom.xml does not contain a `<finalName>` to specify the name for the artifact under the `<build>` tag. Seems like this was never the case, even pre Appsody. In the order microservices this is specified as `${project.artifactId}`, which is why it does not container the version number (which otherwise is the default behaviour).
